"""
preprocess.py
=============
Turns each raw dataset into the same tidy form:

    events       one row per state visit:   customer, time, state, key
    transitions  one row per a -> b step:   customer, a, b, src_time, batch

Nothing downstream of `load_dataset(name)` knows which dataset it is.

State mapping for REES46 clickstream data (see README "Method"):
  * Each session starts with Visitor (inferred, not logged).
  * view -> Product View, cart -> Add to Cart, remove_from_cart -> Product View.
  * All purchase events in one session are one order.
  * Before a customer's first order they move through the browsing funnel;
    a new session starts at Visitor again.
  * From the first order on, the customer moves through ORDER STAGES:
    order 1 -> Purchase, order 2 -> Repeat Purchase, order >= LOYAL_AT ->
    Loyal Customer. Their browsing between orders is not re-entered into the
    funnel. Re-entering it would create Add to Cart -> Loyal edges that let a
    memoryless chain send a brand-new visitor straight to "Loyal".
  * Exit = churn: appended after the last activity if the customer is then
    inactive for CHURN_DAYS before the data ends; otherwise right-censored.
  * Only transitions whose source event is at least CHURN_DAYS before the
    end of the data are used: for later events the outcome is not yet known.
  * Customers are identified by small integer codes. The raw user_ids are
    19-digit numbers that float64 cannot tell apart, which silently merged
    neighbouring customers in an earlier prototype.
"""

import glob
import os
import hashlib
import pickle
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from .. import config
from ..engine.states import STATES, IDX, EXIT

PREPROCESS_VERSION = 4
SYNTHETIC_AOV = 60.0   # synthetic data has no prices; a fixed order value keeps revenue KPIs defined

REGISTRY = {
    "electronics": {
        "label": "REES46 Electronics store",
        "kind": "rees46",
        "pattern": "electronics/*.csv",
        "sample_mod": None,
        "source": "https://www.kaggle.com/datasets/mkechinov/ecommerce-events-history-in-electronics-store",
        "attribution": "Data: REES46 Marketing Platform (rees46.com), via Kaggle (mkechinov).",
    },
    "cosmetics": {
        "label": "REES46 Cosmetics shop",
        "kind": "rees46",
        "pattern": "cosmetics/*.csv",
        "sample_mod": 10,          # keep users with user_id % 10 == 0  (a 10% sample by customer)
        "source": "https://www.kaggle.com/datasets/mkechinov/ecommerce-events-history-in-cosmetics-shop",
        "attribution": "Data: REES46 Marketing Platform (rees46.com), via Kaggle (mkechinov).",
    },
    "synthetic": {
        "label": "Synthetic (planted drift)",
        "kind": "tidy",
        "pattern": "../synthetic/synthetic_customer_events.csv",
        "sample_mod": None,
        "source": "Generated for this project: Cart → Purchase raised from 0.35 to 0.50 in February.",
        "attribution": "Synthetic data generated by the project team.",
    },
}

EXPECTED_COLUMNS = ["event_time", "event_type", "product_id", "category_id", "category_code",
                    "brand", "price", "user_id", "user_session"]


@dataclass
class Dataset:
    name: str
    label: str
    events: pd.DataFrame
    transitions: pd.DataFrame
    batch_labels: List[str]
    aov: float
    facts: Dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Registry helpers
# ---------------------------------------------------------------------------
def _files(name: str) -> List[Path]:
    spec = REGISTRY[name]
    # normpath resolves the "../synthetic" pattern even when data/raw/ does not exist (a fresh clone)
    return sorted(Path(p) for p in glob.glob(os.path.normpath(str(config.RAW_DIR / spec["pattern"]))))


def available_datasets() -> List[Dict]:
    out = []
    for name, spec in REGISTRY.items():
        files = _files(name)
        out.append({"name": name, "label": spec["label"], "available": bool(files),
                    "source": spec["source"], "files": [f.name for f in files]})
    return out


def _cache_path(name: str) -> Path:
    files = _files(name)
    stamp = "_".join(f"{f.name}:{f.stat().st_size}" for f in files)
    digest = hashlib.md5(stamp.encode()).hexdigest()[:10]
    key = f"{name}_v{PREPROCESS_VERSION}_c{config.CHURN_DAYS}_l{config.LOYAL_AT}_{digest}"
    return config.PROCESSED_DIR / f"{key}.pkl"


def load_dataset(name: str, use_cache: bool = True) -> Dataset:
    if name not in REGISTRY:
        raise ValueError(f"unknown dataset '{name}'. Known: {list(REGISTRY)}")
    files = _files(name)
    if not files:
        raise FileNotFoundError(f"No files for '{name}'. Put them in {config.RAW_DIR / REGISTRY[name]['pattern']}")
    cache = _cache_path(name)
    if use_cache and cache.exists():
        try:
            with open(cache, "rb") as fh:
                return pickle.load(fh)
        except Exception:
            cache.unlink(missing_ok=True)       # stale or incompatible cache: rebuild
    spec = REGISTRY[name]
    ds = _load_rees46(name, spec, files) if spec["kind"] == "rees46" else _load_tidy(name, spec, files[0])
    config.PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    with open(cache, "wb") as fh:
        pickle.dump(ds, fh)
    return ds


# ---------------------------------------------------------------------------
# REES46 clickstream -> states
# ---------------------------------------------------------------------------
def _read_rees46(files: List[Path], sample_mod: Optional[int]) -> pd.DataFrame:
    parts = []
    for f in files:
        header = list(pd.read_csv(f, nrows=0).columns)
        if header != EXPECTED_COLUMNS:
            raise ValueError(f"{f.name}: columns {header} differ from the REES46 format {EXPECTED_COLUMNS}")
        for chunk in pd.read_csv(f, usecols=["event_time", "event_type", "product_id", "price", "user_id",
                                             "user_session"],
                                 dtype={"user_id": "int64", "event_type": "category"}, chunksize=2_000_000):
            if sample_mod:
                chunk = chunk[chunk.user_id % sample_mod == 0]
            parts.append(chunk)
    return pd.concat(parts, ignore_index=True)


def order_stage(n: np.ndarray, loyal_at: int = None) -> np.ndarray:
    """Order number (1, 2, 3, ...) -> state index."""
    loyal_at = loyal_at or config.LOYAL_AT
    n = np.asarray(n)
    return np.where(n >= loyal_at, IDX["Loyal Customer"],
                    np.where(n == 1, IDX["Purchase"], IDX["Repeat Purchase"]))


def map_clickstream(df: pd.DataFrame, end: pd.Timestamp, churn_days: int = None,
                    loyal_at: int = None) -> pd.DataFrame:
    """
    Core mapping. `df` needs columns t (datetime), event_type, price,
    uid (int code), sid (int code). Returns tidy events sorted by customer
    and sequence key: columns customer, time, state, value.
    """
    churn = pd.Timedelta(days=churn_days or config.CHURN_DAYS)
    df = df.copy()
    df["sstart"] = df.groupby(["uid", "sid"]).t.transform("min")
    df = df.sort_values(["uid", "sstart", "sid", "t"], kind="mergesort").reset_index(drop=True)
    pos = np.arange(len(df), dtype=float)
    et = df.event_type.astype(str).to_numpy()
    is_p = et == "purchase"

    grp = [df.uid, df.sid]
    order_row = is_p & (pd.Series(is_p).groupby(grp).cumsum().to_numpy() == 1)
    order_no = pd.Series(order_row.astype(int)).groupby(df.uid).cumsum().to_numpy()
    seen_before = order_no - order_row.astype(int)
    value = pd.Series(np.where(is_p, df.price.to_numpy(), 0.0)).groupby(grp).transform("sum").to_numpy()

    # 1) browsing funnel, up to and including the first order
    pre = seen_before == 0
    funnel_state = np.select([et == "view", et == "cart", et == "remove_from_cart", is_p],
                             [IDX["Product View"], IDX["Add to Cart"], IDX["Product View"], IDX["Purchase"]], -1)
    keep = pre & (funnel_state >= 0) & (~is_p | order_row)
    ev = pd.DataFrame({"customer": df.uid[keep].to_numpy(), "key": pos[keep], "time": df.t[keep].to_numpy(),
                       "state": funnel_state[keep], "value": np.where(order_row[keep], value[keep], 0.0)})

    # 2) a Visitor row at the start of every session that has funnel rows
    first_idx = df[keep].groupby(["uid", "sid"], sort=False).head(1).index.to_numpy()
    first_in_sess = np.zeros(len(df), dtype=bool)
    first_in_sess[first_idx] = True
    vis = pd.DataFrame({"customer": df.uid[first_in_sess].to_numpy(), "key": pos[first_in_sess] - 0.5,
                        "time": df.t[first_in_sess].to_numpy(), "state": IDX["Visitor"], "value": 0.0})

    # 3) later orders move the customer through the order stages
    later = order_row & (order_no >= 2)
    life = pd.DataFrame({"customer": df.uid[later].to_numpy(), "key": pos[later], "time": df.t[later].to_numpy(),
                         "state": order_stage(order_no[later], loyal_at), "value": value[later]})

    # 4) churn: Exit after the last activity if inactive for `churn` before the end
    last = df.groupby("uid").t.max()
    churned = last[last <= end - churn]
    ex = pd.DataFrame({"customer": churned.index.to_numpy(), "key": np.inf,
                       "time": (churned + churn).to_numpy(), "state": EXIT, "value": 0.0})

    out = pd.concat([vis, ev, life, ex], ignore_index=True)
    out = out.sort_values(["customer", "key"], kind="mergesort").reset_index(drop=True)
    out["state"] = out.state.astype(int)
    return out


def transitions_from_events(events: pd.DataFrame) -> pd.DataFrame:
    """Consecutive rows of the same customer -> transitions (integer compare only)."""
    c = events.customer.to_numpy()
    same = c[:-1] == c[1:]
    s = events.state.to_numpy()
    t = events.time.to_numpy()
    return pd.DataFrame({"customer": c[:-1][same], "a": s[:-1][same], "b": s[1:][same],
                         "src_time": t[:-1][same], "dst_time": t[1:][same]})


def monthly_batches(tr: pd.DataFrame, start: pd.Timestamp, cutoff: pd.Timestamp) -> (pd.DataFrame, List[str]):
    """Batch by the month of the source event; merge a short first/last month into its neighbour."""
    tr = tr.copy()
    month = pd.to_datetime(tr.src_time).dt.to_period("M")
    months = sorted(month.unique())
    if len(months) > 1:
        first, last = months[0], months[-1]
        if (first.end_time - start).days + 1 < config.MIN_BATCH_DAYS:
            month = month.where(month != first, months[1])
        if (cutoff - last.start_time).days + 1 < config.MIN_BATCH_DAYS and len(months) > 2:
            month = month.where(month != last, months[-2])
    months = sorted(month.unique())
    labels = [m.strftime("%b %Y") for m in months]
    tr["batch"] = month.map({m: k for k, m in enumerate(months)}).astype(int).to_numpy()
    return tr, labels


def _load_rees46(name: str, spec: Dict, files: List[Path]) -> Dataset:
    raw = _read_rees46(files, spec["sample_mod"])
    n_raw = len(raw)
    dups = int(raw.duplicated().sum())
    raw = raw.drop_duplicates()
    null_sess = int(raw.user_session.isna().sum())
    raw = raw.dropna(subset=["user_session"])
    raw["t"] = pd.to_datetime(raw.event_time.str.replace(" UTC", "", regex=False), format="%Y-%m-%d %H:%M:%S")
    raw["uid"] = pd.factorize(raw.user_id)[0]
    raw["sid"] = pd.factorize(raw.user_session)[0]
    start, end = raw.t.min(), raw.t.max()
    cutoff = end - pd.Timedelta(days=config.CHURN_DAYS)

    events = map_clickstream(raw, end)
    tr = transitions_from_events(events)
    n_all = len(tr)
    tr = tr[tr.src_time <= cutoff]
    tr, labels = monthly_batches(tr, start, cutoff)

    # facts for the Data & Method page
    et = raw.event_type.astype(str)
    sess = raw.assign(c=et.eq("cart"), p=et.eq("purchase")).groupby(["uid", "sid"])[["c", "p"]].any()
    orders = events[events.state.isin([IDX["Purchase"], IDX["Repeat Purchase"], IDX["Loyal Customer"]])]
    per_user = orders.groupby("customer").size()
    last = raw.groupby("uid").t.max()
    facts = {
        "rows_raw": n_raw, "duplicates_removed": dups, "null_session_rows_removed": null_sess,
        "rows_used": int(len(raw)), "customers": int(raw.uid.nunique()), "sessions": int(len(sess)),
        "start": str(start), "end": str(end), "cutoff": str(cutoff),
        "event_counts": {k: int(v) for k, v in et.value_counts().items()},
        "orders": int(len(orders)), "buyers": int(len(per_user)),
        "buyers_2plus": int((per_user >= 2).sum()), "buyers_3plus": int((per_user >= 3).sum()),
        "cart_sessions": int(sess.c.sum()),
        "cart_abandonment": float(1 - (sess.c & sess.p).sum() / max(1, sess.c.sum())),
        "order_sessions_without_cart": int((sess.p & ~sess.c).sum()),
        "censored_share": float((last > cutoff).mean()),
        "transitions_total": n_all, "transitions_used": int(len(tr)),
        "sampled": bool(spec["sample_mod"]),
        "sample_rule": f"user_id % {spec['sample_mod']} == 0" if spec["sample_mod"] else "full data",
        "state_counts": {STATES[k]: int(v) for k, v in events.state.value_counts().sort_index().items()},
        "churn_days": config.CHURN_DAYS, "loyal_at": config.LOYAL_AT,
        "source": spec["source"], "attribution": spec["attribution"],
    }
    aov = float(orders.value.mean()) if len(orders) else SYNTHETIC_AOV
    facts["aov"] = aov
    return Dataset(name, spec["label"], events, tr, labels, aov, facts)


# ---------------------------------------------------------------------------
# Already-tidy data (the synthetic set)
# ---------------------------------------------------------------------------
def _load_tidy(name: str, spec: Dict, path: Path) -> Dataset:
    df = pd.read_csv(path, parse_dates=["timestamp"])
    unknown = set(df.event) - set(STATES)
    if unknown:
        raise ValueError(f"{path.name}: unknown states {unknown}")
    df["customer"] = pd.factorize(df.customer_id)[0]
    df = df.reset_index().sort_values(["customer", "timestamp", "index"], kind="mergesort")
    events = pd.DataFrame({"customer": df.customer.to_numpy(), "key": np.arange(len(df), dtype=float),
                           "time": df.timestamp.to_numpy(), "state": df.event.map(IDX).to_numpy(),
                           "value": np.where(df.event.isin(["Purchase", "Repeat Purchase", "Loyal Customer"]),
                                             SYNTHETIC_AOV, 0.0)})
    tr = transitions_from_events(events)
    src = pd.to_datetime(tr.src_time)
    # four half-month batches: two before the planted shift, two after
    key = src.dt.to_period("M").astype(str) + np.where(src.dt.day <= 7, "a", "b")
    keys = sorted(key.unique())
    tr["batch"] = key.map({k: i for i, k in enumerate(keys)}).to_numpy()
    labels = [pd.Period(k[:-1]).strftime("%b") + (" 1–7" if k.endswith("a") else " 8–15") for k in keys]
    facts = {
        "rows_raw": int(len(df)), "customers": int(df.customer.nunique()),
        "start": str(df.timestamp.min()), "end": str(df.timestamp.max()),
        "event_counts": {k: int(v) for k, v in df.event.value_counts().items()},
        "transitions_total": int(len(tr)), "transitions_used": int(len(tr)),
        "sampled": False, "sample_rule": "full data", "complete_journeys": True,
        "state_counts": {k: int(v) for k, v in df.event.value_counts().items()},
        "aov": SYNTHETIC_AOV, "aov_note": "fixed value; synthetic data has no prices",
        "source": spec["source"], "attribution": spec["attribution"],
    }
    return Dataset(name, spec["label"], events, tr, labels, SYNTHETIC_AOV, facts)
